import {
  Landmark,
  Wallet,
  UserCircle,
  Plus,
  ChartNoAxesCombined,
  Building2,
  BadgeCheck,
  Archive,
  ArrowLeft,
  ArrowRight,
  Sparkles,
  RefreshCw,
  Bath,
  Bed,
  Ban,
  Zap,
  Wrench,
  Briefcase,
  Calendar,
  Phone,
  Megaphone,
  XCircle,
  Armchair,
  MessageCircle,
  Check,
  CheckCircle2,
  Copy,
  ListChecks,
  ChevronLeft,
  ChevronRight,
  X,
  CloudOff,
  Ticket,
  Building,
  CreditCard,
  LayoutDashboard,
  Trash2,
  FileText,
  DoorOpen,
  Download,
  FileEdit,
  Pencil,
  NotebookPen,
  AlertCircle,
  CalendarDays,
  CalendarCheck,
  ChevronDown,
  ClipboardCheck,
  Heart,
  Filter,
  Plane,
  Folder,
  FolderOpen,
  MessageSquare,
  Gavel,
  Users,
  Handshake,
  Hammer,
  History,
  ScrollText,
  Home,
  Hourglass,
  Share2,
  Info,
  LineChart,
  Smartphone,
  Share,
  KeyRound,
  Mountain,
  ClipboardList,
  ParkingSquare,
  MapPin,
  LogOut,
  Mail,
  UserCog,
  Map,
  MailCheck,
  Presentation,
  Menu,
  BookOpen,
  MoreHorizontal,
  Truck,
  FilePlus,
  Bell,
  ExternalLink,
  Banknote,
  Clock,
  Percent,
  User,
  UserPlus,
  Camera,
  Images,
  Tag,
  Loader2,
  Globe,
  UploadCloud,
  Receipt,
  ReceiptText,
  Calculator,
  Rocket,
  Route,
  Save,
  PiggyBank,
  Search,
  SearchX,
  Send,
  Bot,
  Ruler,
  Star,
  Store,
  Headset,
  ArrowLeftRight,
  CircleCheckBig,
  TrendingUp,
  SlidersHorizontal,
  Undo2,
  Upload,
  FileUp,
  ShieldCheck,
  Eye,
  Warehouse,
  AlertTriangle,
  HelpCircle,
  type LucideIcon,
} from "lucide-react";

/** Material Symbols name -> lucide-react component. Keeps every call site
 *  (`<Icon name="search" />`) unchanged while the render swaps from
 *  ligature-font glyphs to real SVG icons. */
const ICONS: Record<string, LucideIcon> = {
  account_balance: Landmark,
  account_balance_wallet: Wallet,
  account_circle: UserCircle,
  add: Plus,
  analytics: ChartNoAxesCombined,
  apartment: Building2,
  approval: BadgeCheck,
  archive: Archive,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkles,
  autorenew: RefreshCw,
  bathtub: Bath,
  bed: Bed,
  block: Ban,
  bolt: Zap,
  build: Wrench,
  business: Briefcase,
  business_center: Briefcase,
  calendar_month: Calendar,
  call: Phone,
  campaign: Megaphone,
  cancel: XCircle,
  chair: Armchair,
  chat: MessageCircle,
  check: Check,
  check_circle: CheckCircle2,
  checklist: ListChecks,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  cloud_off: CloudOff,
  confirmation_number: Ticket,
  contact_phone: Phone,
  content_copy: Copy,
  corporate_fare: Building,
  credit_card: CreditCard,
  dashboard: LayoutDashboard,
  delete: Trash2,
  description: FileText,
  door_front: DoorOpen,
  download: Download,
  draft: FileEdit,
  drive_folder_upload: FileUp,
  edit: Pencil,
  edit_document: FileEdit,
  edit_note: NotebookPen,
  error: AlertCircle,
  event: CalendarDays,
  event_available: CalendarCheck,
  expand_more: ChevronDown,
  fact_check: ClipboardCheck,
  favorite: Heart,
  filter_alt: Filter,
  flight: Plane,
  folder: Folder,
  folder_open: FolderOpen,
  forum: MessageSquare,
  forward: ArrowRight,
  gavel: Gavel,
  groups: Users,
  handshake: Handshake,
  handyman: Hammer,
  history: History,
  history_edu: ScrollText,
  home: Home,
  home_work: Building2,
  hourglass_top: Hourglass,
  hub: Share2,
  info: Info,
  insights: LineChart,
  install_mobile: Smartphone,
  ios_share: Share,
  key: KeyRound,
  landscape: Mountain,
  list_alt: ClipboardList,
  local_parking: ParkingSquare,
  location_on: MapPin,
  logout: LogOut,
  mail: Mail,
  manage_accounts: UserCog,
  map: Map,
  mark_email_read: MailCheck,
  meeting_room: Presentation,
  menu: Menu,
  menu_book: BookOpen,
  more_horiz: MoreHorizontal,
  moving: Truck,
  note_add: FilePlus,
  notifications: Bell,
  open_in_new: ExternalLink,
  payments: Banknote,
  pending: Clock,
  percent: Percent,
  person: User,
  person_add: UserPlus,
  photo_camera: Camera,
  photo_library: Images,
  picture_as_pdf: FileText,
  post_add: FilePlus,
  price_check: Tag,
  progress_activity: Loader2,
  public: Globe,
  publish: UploadCloud,
  real_estate_agent: Handshake,
  receipt: Receipt,
  receipt_long: ReceiptText,
  refresh: RefreshCw,
  request_quote: Calculator,
  rocket_launch: Rocket,
  route: Route,
  save: Save,
  savings: PiggyBank,
  schedule: Clock,
  search: Search,
  search_off: SearchX,
  sell: Tag,
  send: Send,
  share: Share2,
  smart_toy: Bot,
  sms: MessageSquare,
  square_foot: Ruler,
  star: Star,
  storefront: Store,
  support_agent: Headset,
  swap_horiz: ArrowLeftRight,
  task_alt: CircleCheckBig,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  undo: Undo2,
  upload: Upload,
  upload_file: FileUp,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  visibility: Eye,
  warehouse: Warehouse,
  warning: AlertTriangle,
  weekend: CalendarDays,
  work: Briefcase,
};

type IconProps = {
  /** Icon key — see the ICONS lookup table above. */
  name: string;
  className?: string;
  /** Pixel size (width + height). */
  size?: number;
  /** 0 = outline (default), 1 = filled. */
  fill?: 0 | 1;
  /** Stroke weight, loosely following the old 100-700 Material scale. */
  weight?: number;
  "aria-hidden"?: boolean;
};

/**
 * Thin wrapper over lucide-react. Inherits `currentColor`, so colour it with
 * text-* utilities on a parent. `name` keys are the site's own vocabulary
 * (originally Material Symbols names); see the ICONS map for the mapping.
 */
export function Icon({
  name,
  className,
  size = 24,
  fill = 0,
  weight = 400,
  "aria-hidden": ariaHidden = true,
}: IconProps) {
  const Glyph = ICONS[name] ?? HelpCircle;
  const strokeWidth = Math.min(2.75, Math.max(1.25, (weight / 400) * 2));
  return (
    <Glyph
      aria-hidden={ariaHidden}
      className={`select-none${className ? ` ${className}` : ""}`}
      width={size}
      height={size}
      strokeWidth={strokeWidth}
      fill={fill ? "currentColor" : "none"}
    />
  );
}
