import { site } from "@/lib/site";

export type Settings = Record<string, string>;

export const settingsFallback: Settings = {
  contact_phone:        site.phone,
  contact_email:        site.email,
  contact_location:     site.location,
  contact_service_area: site.serviceArea,
  social_facebook:      site.facebook,
  social_messenger:     site.messenger,
  social_whatsapp:      site.whatsapp,
  social_viber:         site.viber,
  brand_tagline:        site.tagline,
  brand_descriptor:     site.descriptor,
  hero_heading:         "All Abode Property Solutions",
  hero_subheading:      "Licensed real estate brokerage, valuation, leasing, and property management services for property owners, buyers, sellers, tenants, and investors.",
  hero_body:            "All Abode helps you handle real estate with more confidence. Whether you are buying, selling, leasing, managing, or valuing a property, our team provides practical support from inquiry to completion.",
  hero_image:           "",
  hero_image_position:  "center",
  page_about_image:     "",
  page_about_image_position:     "center",
  page_leasing_image:   "",
  page_leasing_image_position:   "center",
  page_buysell_image:   "",
  page_buysell_image_position:   "center",
  page_pm_image:        "",
  page_pm_image_position:        "center",
  page_appraisal_image: "",
  page_appraisal_image_position: "center",
  page_contact_image:   "",
  page_contact_image_position:   "center",
  page_listings_image:  "",
  page_listings_image_position:  "center",
  page_listyour_image:  "",
  page_listyour_image_position:  "center",
  page_resources_image: "",
  page_resources_image_position: "center",
  page_property_solutions_image: "",
  page_property_solutions_image_position: "center",
  page_documentation_image:      "",
  page_documentation_image_position:      "center",
  page_faq_image:                "",
  page_faq_image_position:                "center",
  page_terms_image:              "",
  page_terms_image_position:              "center",
  page_privacy_image:            "",
  page_privacy_image_position:            "center",
  page_cookie_image:             "",
  page_cookie_image_position:             "center",
};

export function s(settings: Settings, key: string): string {
  return settings[key] ?? settingsFallback[key] ?? "";
}

export const settingsSchema = [
  {
    group: "contact",
    title: "Contact Information",
    icon: "contact_phone",
    fields: [
      { key: "contact_phone",        label: "Phone",               type: "tel" },
      { key: "contact_email",        label: "Email",               type: "email" },
      { key: "contact_location",     label: "Location / Address",  type: "text" },
      { key: "contact_service_area", label: "Service Area",        type: "text" },
    ],
  },
  {
    group: "social",
    title: "Social & Messaging",
    icon: "share",
    fields: [
      { key: "social_facebook",  label: "Facebook URL",   type: "url" },
      { key: "social_messenger", label: "Messenger URL",  type: "url" },
      { key: "social_whatsapp",  label: "WhatsApp URL",   type: "url" },
      { key: "social_viber",     label: "Viber URL",      type: "url" },
    ],
  },
  {
    group: "brand",
    title: "Brand & Identity",
    icon: "business",
    fields: [
      { key: "brand_tagline",    label: "Tagline",                               type: "text" },
      { key: "brand_descriptor", label: "Descriptor (shown in footer / header)", type: "text" },
    ],
  },
  {
    group: "hero",
    title: "Home Page Hero",
    icon: "home",
    fields: [
      { key: "hero_heading",    label: "Heading",          type: "text" },
      { key: "hero_subheading", label: "Subheading",       type: "text" },
      { key: "hero_body",       label: "Body Text",        type: "textarea" },
      { key: "hero_image",      label: "Background Image", type: "image" },
      { key: "hero_image_position", label: "Background Image Position", type: "position" },
    ],
  },
  {
    group: "page_heroes",
    title: "Page Hero Backgrounds",
    icon: "photo_library",
    fields: [
      { key: "page_about_image",     label: "About — Background Image",               type: "image" },
      { key: "page_about_image_position",     label: "About — Image Position",               type: "position" },
      { key: "page_leasing_image",   label: "Leasing — Background Image",             type: "image" },
      { key: "page_leasing_image_position",   label: "Leasing — Image Position",             type: "position" },
      { key: "page_buysell_image",   label: "Buy & Sell — Background Image",          type: "image" },
      { key: "page_buysell_image_position",   label: "Buy & Sell — Image Position",          type: "position" },
      { key: "page_pm_image",        label: "Property Management — Background Image", type: "image" },
      { key: "page_pm_image_position",        label: "Property Management — Image Position", type: "position" },
      { key: "page_appraisal_image", label: "Appraisal — Background Image",          type: "image" },
      { key: "page_appraisal_image_position", label: "Appraisal — Image Position",          type: "position" },
      { key: "page_contact_image",   label: "Contact — Background Image",             type: "image" },
      { key: "page_contact_image_position",   label: "Contact — Image Position",             type: "position" },
      { key: "page_listings_image",  label: "Listings — Background Image",            type: "image" },
      { key: "page_listings_image_position",  label: "Listings — Image Position",            type: "position" },
      { key: "page_listyour_image",  label: "List Your Property — Background Image",  type: "image" },
      { key: "page_listyour_image_position",  label: "List Your Property — Image Position",  type: "position" },
      { key: "page_resources_image", label: "Resources — Background Image",           type: "image" },
      { key: "page_resources_image_position", label: "Resources — Image Position",           type: "position" },
      { key: "page_property_solutions_image", label: "All Services — Background Image", type: "image" },
      { key: "page_property_solutions_image_position", label: "All Services — Image Position", type: "position" },
      { key: "page_documentation_image",      label: "Documentation Assistance — Background Image", type: "image" },
      { key: "page_documentation_image_position",      label: "Documentation Assistance — Image Position", type: "position" },
      { key: "page_faq_image",                label: "FAQ — Background Image", type: "image" },
      { key: "page_faq_image_position",                label: "FAQ — Image Position", type: "position" },
      { key: "page_terms_image",              label: "Terms of Service — Background Image", type: "image" },
      { key: "page_terms_image_position",              label: "Terms of Service — Image Position", type: "position" },
      { key: "page_privacy_image",            label: "Privacy Policy — Background Image", type: "image" },
      { key: "page_privacy_image_position",            label: "Privacy Policy — Image Position", type: "position" },
      { key: "page_cookie_image",              label: "Cookie Policy — Background Image", type: "image" },
      { key: "page_cookie_image_position",              label: "Cookie Policy — Image Position", type: "position" },
    ],
  },
] as const;
